### PR TITLE
Add stacks correctly

### PR DESCRIPTION
**Pull request by wozaiha**
This pr made a change that make StatusManager correctly update status.stacks instead of add it by 1.
When the request is made by StatusTuple, it add 'newstatus.stacks' onto the old ones (it add only 1 before the fix).
And also it will overwrite the stacks when the request is made by DataString (it dont update stacks and keep the old data before the fix).

### CODE REVIEW

**Comment by Glyceri** [comment]
This was made by @CordeliaMist so I want her to sign off on this as well. But it looks good to me, the old code is indeed wrong in that regard.

**Comment by CordeliaMist** [comment]
the intended behavior is to keep the current stacks if applied by a data string with stackOnReapply, and to add 1 to it if it is performed by a status tuple.

If you were to allow the stacks to be increased or prevent it from keeping current stack count with stackOnReapply active, mare will force moodles to apply any "stackOnReapply" actions twice for every modification made.

Im unsure how this is a bug in the first place, or what this fix is even doing? To me it looks like all it will do is re-introduce the previous problem

**Comment by CordeliaMist** [comment]
From a glance this looks like if you were to reapply something from 2 stacks to 3 on moodles, mare would try to update it and send 3, which is fine. if a plugin like GSpeak reapplied the status, it would apply the affect once, bumping it from 2 to 3, then mare would recieve the update seeing it as 3, and add 3 to it making it 6?

**Comment by CordeliaMist** [comment]
Would this be a more efficient approach? We wouldnt need to run the checks for the commonProcessor this way if its a data string and not have to worry about count missmatches.

```csharp
// check to see if the status is already present.
for (var i = 0; i < Statuses.Count; i++)
{
    if(Statuses[i].GUID == newStatus.GUID)
    {
        // use newStatus to check, in case we changed the setting between applications. Performs stack count updating.
        if (newStatus.StackOnReapply)
        {
            if (source is UpdateSource.StatusTuple)
            {
                // grab the current stack count.
                var newStackCount = Statuses[i].Stacks;
                // fetch what the max stack count for the icon is.
                if (P.CommonProcessor.IconStackCounts.TryGetValue((uint)newStatus.IconID, out var max))
                {
                    // if the stack count is less than the max, increase it by 1, and remove it from addTextShown to display the new stack.
                    if (Statuses[i].Stacks + 1 <= max)
                    {
                        newStackCount++;
                        newStatus.Stacks = newStackCount;
                        AddTextShown.Remove(newStatus.GUID);
                    }
                }
            }
            // Handle sources that are from status manager sets.
            else if (source is UpdateSource.DataString)
            {
                // if the source is the data string, we simply apply the data string.
                // HOWEVER, if and only if the stack count is different, we need to remove it from addTextShown to display the new stack.
                if (Statuses[i].Stacks != newStatus.Stacks)
                    AddTextShown.Remove(newStatus.GUID);
            }
        }
        // then update the status with the new status.
        Statuses[i] = newStatus;
        // fire trigger if needed and then early return.
        if(triggerEvent) NeedFireEvent = true;
        return;
    }
}
// if it was new, fire event if needed and add it.
if (triggerEvent) NeedFireEvent = true;
Statuses.Add(newStatus);
```

**Comment by wozaiha** [comment]
An example for the pr:
Let's say we have a moodles status: { Title: blabla, AddStackOnReapply: true, stacks: 2, Duration: 5mins (whatever), ...}
And a player "A Player" who already have 4 stacks of this status.

If someone add this status to "A Player" again, this will happen:
Before this fix: He get messaged through Gagspeak or some other sync plugins. -> This is an "StatusTruple" event so the stacks will be added by 1 (as a result: 5 stacks). -> Mare catched this edit and fired an update event to his mare pairs. -> His partner's Moodles received this update event (which should be an "DataString" event with 5 stacks). -> His partner's Moodles update the status shows on their side (duration or whatever) but leave the stacks not edited (4 stacks).
This will result a different. And I think it should add 2 stacks instead of 1 since the status have 2 stacks. That is why I think it is a bug whatever.

What will happen after this pr:
"A player"'s Moodles received the update message. -> Moodles received this event (StatusTuple). -> Add stacks by 2 (so it will be 6). -> Mare fires an update event.  -> His partner received the update message (DataString, 6 stacks). -> His partner's Moodles updates the status and overwrite the stacks with the new one. -> Stacks changed to 6. 
So we will have the result that both sides have 6 stacks. 
This is why I made this pr, if anything was incorrect please let me know. Thanks.

**Comment by CordeliaMist** [comment]
Ah i see the confusion you have. The stacks is not how many stacks at once should be applied per reapplication, its the initial stack to set.

Hince the modification i made in accordance to your formula with slight adjustments. I've tested it on both my and and another persons and both sides of the coin seem to work in compatibility with mare

**Comment by CordeliaMist** [comment]
the code block above is the same thing that you suggested, it just puts the dictionary lookup to only happen in the tuple condition, and ensure it only reapplies the appearance when the stack changes are different, and not do it even if they are the same during an update. The way you had it before it would re-display the stacked application even if the change came from another moodle in the manager

**Comment by CordeliaMist** [comment]
just to clarify, the reason why its not a bug that its only going up by one, and not up by the stack count, is that the stack count is nessisary to transmit what the current stack count of the moodle is between pairs, without affecting the MyStatus item in moodles directly.

If it were used like that, it would need to be a different variable in the MyStatus entirely, or else the first stack would go up by 2, then the next by 4, then the next by 8 ext.

**Comment by wozaiha** [comment]
> just to clarify, the reason why its not a bug that its only going up by one, and not up by the stack count, is that the stack count is nessisary to transmit what the current stack count of the moodle is between pairs, without affecting the MyStatus item in moodles directly.
> 
> 
> 
> If it were used like that, it would need to be a different variable in the MyStatus entirely, or else the first stack would go up by 2, then the next by 4, then the next by 8 ext.

I understood what you mean. Then I think we should have 2 variables like "initial stacks" and "stacks added on reapply". 
But I think even if we don't changed it, if the stacks is 2. It will not be 2, 4, 8 but 2, 4, 6.

**Comment by Glyceri** [comment]
I agree with the 2 variable approach. 1 for initial and 1 for future applications seems good.

**Comment by CordeliaMist** [comment]
I can put something together and update all of the other information ill need my plugin to be compatible with that in that case later this evening... It will need to have more appended beyond just a change to the statuses or else it will cause issues with mare's handling.

**Comment by Glyceri** [comment]
What a pain. This is your fault @kawaii life was fun before moodles became ""mine""

**Comment by wozaiha** [comment]
I think Mare will be ok but gagspeak needs some update since the status data is transferred directly. Maybe an api update is needed?

**Comment by CordeliaMist** [comment]
> I think Mare will be ok but gagspeak needs some update since the status data is transferred directly. Maybe an api update is needed?

Correct, ive gone ahead and made all nessisary changes moodles would need to make over here while aligning with the tuple requirements StatusTuple users need to make 👍 
https://github.com/kawaii/Moodles/pull/59#issue-2739039280

**Pull request closed without merging**
